from __future__ import annotations

from dataclasses import dataclass
from typing import Literal

SettingType = Literal["str", "int", "float", "bool", "secret"]

# Only used before SQLite exists; everything else is web-configurable in DB.
BOOTSTRAP_ENV_KEYS = frozenset({"DATA_DIR"})

SECRET_KEYS = frozenset({
    "FLASK_SECRET_KEY",
    "LLM_API_KEY",
    "LDAP_BIND_PASSWORD",
    "LOCAL_AUTH_PASSWORD",
    "SMTP_PASSWORD",
    "MIST_API_KEY",
    "WEBHOOK_INGEST_SECRET",
})

SETUP_COMPLETE_KEY = "SETUP_COMPLETE"


@dataclass(frozen=True)
class SettingDef:
    key: str
    default: str
    value_type: SettingType
    section: str
    label: str
    description: str = ""
    requires_restart: bool = False


def registry() -> list[SettingDef]:
    return [
        SettingDef("FLASK_HOST", "0.0.0.0", "str", "server", "Bind address", requires_restart=True),
        SettingDef("FLASK_PORT", "9080", "int", "server", "HTTP port", requires_restart=True),
        SettingDef("DATA_DIR", "./data", "str", "server", "Data directory", requires_restart=True),
        SettingDef("FLASK_SECRET_KEY", "", "secret", "server", "Session secret key", requires_restart=True),
        SettingDef("LOG_DIR", "/var/log", "str", "logging", "Log directory", "Used when LOG_DIRS is empty"),
        SettingDef("LOG_DIRS", "", "str", "logging", "Log directories", "Comma-separated roots", True),
        SettingDef("LOG_GLOB", "*", "str", "logging", "File glob", requires_restart=True),
        SettingDef("LOG_RECURSIVE", "0", "bool", "logging", "Recursive scan", requires_restart=True),
        SettingDef("LOG_READ_COMPRESSED", "0", "bool", "logging", "List/read .gz logs (no live tail)", requires_restart=True),
        SettingDef("LOG_SKIP_NAMES", "wtmp,btmp,lastlog,faillog,README.logs", "str", "logging", "Skip basenames"),
        SettingDef("JOURNAL_ENABLED", "1", "bool", "logging", "Tail systemd journal (journalctl)", requires_restart=True),
        SettingDef("JOURNAL_DIRECTORY", "", "str", "logging", "Journal directory (-D)", "Docker: /run/log/journal", True),
        SettingDef("JOURNAL_BOOT_ONLY", "0", "bool", "logging", "Current boot only (-b)", requires_restart=True),
        SettingDef("JOURNAL_MERGE_SYSTEM", "0", "bool", "logging", "Merge system journals (--merge)", requires_restart=True),
        SettingDef("JOURNAL_UNITS", "", "str", "logging", "Filter units (-u)", "Comma-separated, e.g. ssh.service,nginx.service", True),
        SettingDef("JOURNAL_PRIORITY", "", "str", "logging", "Min priority", "debug, info, warning, err, …", True),
        SettingDef("JOURNAL_MATCH", "", "str", "logging", "Extra --grep filters", "Comma-separated", True),
        SettingDef("JOURNAL_OUTPUT", "short-iso", "str", "logging", "journalctl output format", requires_restart=True),
        SettingDef("JOURNAL_PAGE_LINES", "500", "int", "logging", "Journal file-view line count"),
        SettingDef("JOURNAL_SEARCH_SINCE", "24 hours ago", "str", "search", "Journal search window"),
        SettingDef("SCAN_INTERVAL_SEC", "5", "float", "logging", "Scan interval (s)", requires_restart=True),
        SettingDef("TAIL_BUFFER_SIZE", "2000", "int", "logging", "Live buffer size", requires_restart=True),
        SettingDef("TAIL_DEFAULT_ORDER", "desc", "str", "logging", "Default sort order"),
        SettingDef("FILE_RECENT_BYTES", "5242880", "int", "logging", "File view tail bytes"),
        SettingDef("SEARCH_MAX_RESULTS", "5000", "int", "search", "Max search results"),
        SettingDef("SEARCH_MAX_BYTES_PER_FILE", "52428800", "int", "search", "Search bytes per file"),
        SettingDef("SEARCH_CASE_SENSITIVE", "0", "bool", "search", "Case-sensitive search"),
        SettingDef("EXPORT_MAX_ROWS", "10000", "int", "search", "Max export rows"),
        SettingDef("LLM_ENABLED", "1", "bool", "llm", "Enable LLM features (explain & anomaly analysis)"),
        SettingDef("LLM_PROVIDER", "ollama", "str", "llm", "LLM provider (ollama, openai, hybrid)"),
        SettingDef("OLLAMA_BASE_URL", "http://127.0.0.1:11434", "str", "llm", "Ollama base URL"),
        SettingDef("OLLAMA_MODEL", "qwen3.6:27b-q8_0", "str", "llm", "Ollama chat model"),
        SettingDef("OLLAMA_EMBED_MODEL", "nomic-embed-text", "str", "llm", "Ollama embed model"),
        SettingDef("OLLAMA_TIMEOUT_SEC", "600", "int", "llm", "Chat timeout (s)"),
        SettingDef("OLLAMA_EMBED_TIMEOUT_SEC", "600", "int", "llm", "Embed timeout (s)"),
        SettingDef("OLLAMA_NUM_PREDICT", "1024", "int", "llm", "Max tokens"),
        SettingDef(
            "OLLAMA_JSON_FORMAT",
            "0",
            "bool",
            "llm",
            "Request JSON format (disable for qwen3.x / thinking models)",
        ),
        SettingDef("LLM_API_BASE_URL", "https://api.openai.com/v1", "str", "llm", "OpenAI-compatible API URL"),
        SettingDef("LLM_API_KEY", "", "secret", "llm", "API key"),
        SettingDef("LLM_CHAT_MODEL", "", "str", "llm", "OpenAI-compatible chat model"),
        SettingDef("LLM_EMBED_MODEL", "text-embedding-3-small", "str", "llm", "OpenAI embed model"),
        SettingDef("LOG_LINE_MAX_CHARS", "4096", "int", "llm", "Max line chars for LLM"),
        SettingDef("LLM_SKIP_LOW_LEVELS", "1", "bool", "llm", "Skip INFO/DEBUG for LLM"),
        SettingDef("LLM_MAX_FILE_BYTES", "20971520", "int", "llm", "Max file bytes for LLM"),
        SettingDef("LLM_DIRECT_MAX_BYTES", "524288", "int", "llm", "Direct LLM max bytes"),
        SettingDef("RAG_CHUNK_LINES", "40", "int", "llm", "RAG chunk lines"),
        SettingDef("RAG_CHUNK_OVERLAP", "8", "int", "llm", "RAG chunk overlap"),
        SettingDef("RAG_TOP_K", "12", "int", "llm", "RAG top K"),
        SettingDef("RAG_MAX_LINES", "200000", "int", "llm", "RAG max lines"),
        SettingDef("RAG_MAX_CHUNKS", "1500", "int", "llm", "RAG max chunks"),
        SettingDef("EMBED_BATCH_SIZE", "8", "int", "llm", "Embed batch size"),
        SettingDef("EMBED_MAX_CHARS", "4000", "int", "llm", "Embed max chars per chunk"),
        SettingDef("EMBED_LINE_MAX_CHARS", "512", "int", "llm", "Embed line max chars"),
        SettingDef(
            "EMBED_MAX_TOKENS_PER_INPUT",
            "512",
            "int",
            "llm",
            "Max tokens per embed input (Berget e5: 512)",
        ),
        SettingDef(
            "EMBED_MAX_TOKENS_PER_REQUEST",
            "512",
            "int",
            "llm",
            "Max total tokens per embed API call (0 = no cap)",
        ),
        SettingDef("EMBED_MAX_RETRIES", "4", "int", "llm", "Embed max retries"),
        SettingDef("RAG_QUERY", "security anomalies errors failures authentication denials", "str", "llm", "RAG query"),
        SettingDef("LLM_AUDIT_ENABLED", "1", "bool", "llm", "Write LLM audit plain log"),
        SettingDef("LLM_AUDIT_LOG", "", "str", "llm", "LLM audit log path (empty = data/llm-audit.log)"),
        SettingDef("LLM_AUDIT_MAX_CHARS", "8000", "int", "llm", "Max chars per request/response in audit log"),
        SettingDef("ANALYSIS_HISTORY_KEEP", "5", "int", "llm", "Saved LLM analyses to keep (1–50)"),
        SettingDef(
            "APP_PUBLIC_URL",
            "",
            "str",
            "llm",
            "Public URL for analysis links in alerts (empty = http://127.0.0.1:FLASK_PORT)",
        ),
        SettingDef("APP_NAME", "log-intel", "str", "branding", "Application name"),
        SettingDef("APP_VERSION", "", "str", "branding", "Version override"),
        SettingDef("BRAND_LOGO", "branding/log-intel.png", "str", "branding", "Logo path or URL"),
        SettingDef("BRAND_LOGO_LINK", "", "str", "branding", "Logo link"),
        SettingDef(
            "BRAND_TAGLINE",
            "Unified log intelligence — files + network syslog",
            "str",
            "branding",
            "Tagline",
        ),
        SettingDef(
            "COPYRIGHT_TEXT",
            "log-intel by Kristinsson Consulting",
            "str",
            "branding",
            "Copyright",
        ),
        SettingDef("AUTH_ENABLED", "0", "bool", "auth", "Require sign-in"),
        SettingDef("LOCAL_AUTH_USERNAME", "admin", "str", "auth", "Local admin username"),
        SettingDef("LOCAL_AUTH_PASSWORD", "", "secret", "auth", "Local admin password"),
        SettingDef("LDAP_URI", "", "str", "auth", "LDAP URI"),
        SettingDef("LDAP_USE_SSL", "0", "bool", "auth", "LDAP SSL"),
        SettingDef("LDAP_TIMEOUT_SEC", "10", "int", "auth", "LDAP timeout"),
        SettingDef("LDAP_BIND_DN", "", "str", "auth", "LDAP bind DN"),
        SettingDef("LDAP_BIND_PASSWORD", "", "secret", "auth", "LDAP bind password"),
        SettingDef("LDAP_USER_DN_TEMPLATE", "", "str", "auth", "LDAP user DN template"),
        SettingDef("LDAP_USER_SEARCH_BASE", "", "str", "auth", "LDAP user search base"),
        SettingDef("LDAP_USER_SEARCH_FILTER", "(sAMAccountName={username})", "str", "auth", "LDAP user filter"),
        SettingDef("LDAP_GROUP_SEARCH_BASE", "", "str", "auth", "LDAP group search base"),
        SettingDef("LDAP_REQUIRED_GROUP", "", "str", "auth", "LDAP required group DN"),
        SettingDef("LDAP_REQUIRED_GROUP_CN", "", "str", "auth", "LDAP required group CN"),
        SettingDef("LDAP_MEMBER_OF_ATTR", "memberOf", "str", "auth", "LDAP memberOf attr"),
        SettingDef("SMTP_HOST", "", "str", "alerts", "SMTP host"),
        SettingDef("SMTP_PORT", "587", "int", "alerts", "SMTP port"),
        SettingDef("SMTP_USER", "", "str", "alerts", "SMTP user"),
        SettingDef("SMTP_PASSWORD", "", "secret", "alerts", "SMTP password"),
        SettingDef("SMTP_FROM", "", "str", "alerts", "SMTP from address"),
        SettingDef("SMTP_TLS", "1", "bool", "alerts", "SMTP TLS"),
        SettingDef("ALERT_MAX_PER_MINUTE", "30", "int", "alerts", "Global alert cap per minute"),
        SettingDef("ALERT_COOLDOWN_SEC", "300", "int", "alerts", "Per-rule cooldown default (seconds)"),
        SettingDef(
            "WEBHOOK_INGEST_SECRET",
            "",
            "secret",
            "alerts",
            "Shared secret for POST /api/v1/webhooks/syslogb (legacy path; file-log alert ingest)",
            "Send as X-Webhook-Secret or Authorization: Bearer …",
        ),
        # --- Hub (network syslog + on-demand LLM) ---
        SettingDef(
            "LOG_INTEL_LLM_ENABLED",
            "1",
            "bool",
            "hub",
            "Enable hub on-demand LLM (/hub/analysis)",
        ),
        SettingDef(
            "LOG_INTEL_ANALYSIS_AUTO",
            "0",
            "bool",
            "hub",
            "Automatic hourly hub batch LLM (uses tokens)",
            "Off by default — use Run window analysis in the hub UI",
        ),
        SettingDef("LOG_INTEL_ANALYSIS_BATCH_SIZE", "3", "int", "hub", "Hub LLM batch size"),
        SettingDef(
            "LOG_INTEL_ANALYSIS_INTERVAL_SEC",
            "3600",
            "int",
            "hub",
            "Seconds between auto hub LLM runs",
            requires_restart=True,
        ),
        SettingDef("ANALYSIS_INTER_BATCH_SLEEP_SEC", "2", "float", "hub", "Pause between hub LLM batches (s)"),
        SettingDef(
            "ANALYSIS_SKIP_BLOCKED_TRAFFIC",
            "1",
            "bool",
            "hub",
            "Auto-skip denied/blocked Palo Alto traffic in hub LLM",
        ),
        SettingDef("ON_DEMAND_MAX_BATCHES", "0", "int", "hub", "On-demand batch cap (0 = unlimited)"),
        SettingDef("ON_DEMAND_MAX_WALL_SEC", "0", "int", "hub", "On-demand time cap seconds (0 = unlimited)"),
        SettingDef("OLLAMA_THINK", "medium", "str", "hub", "Ollama thinking mode (false to disable)"),
        SettingDef("OLLAMA_THINK_MIN_NUM_PREDICT", "4096", "int", "hub", "Min tokens when thinking enabled"),
        SettingDef(
            "META_SUMMARY_ENABLED",
            "0",
            "bool",
            "hub",
            "Scheduled daily meta LLM rollups",
            "Requires prior batch analyses; uses tokens",
        ),
        SettingDef("META_WEEKLY_ENABLED", "0", "bool", "hub", "Include weekly meta rollups"),
        SettingDef("META_DAILY_INTERVAL_SEC", "86400", "int", "hub", "Min seconds between daily meta runs"),
        SettingDef("META_WEEKLY_INTERVAL_SEC", "604800", "int", "hub", "Min seconds between weekly meta runs"),
        SettingDef("META_WORKER_POLL_SEC", "1800", "int", "hub", "Meta worker poll interval (s)"),
        SettingDef("META_MIN_RETRY_SEC", "3600", "int", "hub", "Min retry after failed meta run (s)"),
        SettingDef("META_CONTEXT_MAX_ANALYSES", "80", "int", "hub", "Max analyses in meta context"),
        SettingDef("META_MIN_ANALYSES_DAILY", "2", "int", "hub", "Min analyses before daily meta"),
        SettingDef("META_MIN_ANALYSES_WEEKLY", "4", "int", "hub", "Min analyses before weekly meta"),
        SettingDef("META_OLLAMA_TIMEOUT_SEC", "1800", "int", "hub", "Meta LLM timeout (s)"),
        SettingDef("META_NUM_PREDICT", "2048", "int", "hub", "Meta LLM max tokens"),
        SettingDef("MAX_META_SUMMARIES", "2000", "int", "hub", "Retained meta summary rows"),
        SettingDef("MAX_ANALYSES", "5000", "int", "hub", "Retained hub analysis rows"),
        SettingDef("LOG_INTEL_RETENTION_HOURS", "168", "float", "hub", "Hub event retention (0 = forever)"),
        SettingDef("LOG_INTEL_MAX_EVENTS", "500000", "int", "hub", "Max hub events in SQLite"),
        SettingDef("LOG_INTEL_QUEUE_MAXSIZE", "50000", "int", "hub", "Syslog ingest queue size", True),
        SettingDef("LOG_INTEL_RAW_TRUNCATE", "2048", "int", "hub", "Truncate raw syslog per event"),
        SettingDef(
            "LOG_INTEL_GEOIP_MMDB_PATH",
            "./geoip/dbip-city-lite.mmdb",
            "str",
            "hub",
            "GeoIP database path",
        ),
        SettingDef("LOG_INTEL_LOG_LEVEL", "INFO", "str", "hub", "Log level"),
        SettingDef("LOGGY_DB_PATH", "", "str", "hub", "Read-only loggy archive DB path"),
        SettingDef("NETSYSLOG_DB_PATH", "", "str", "hub", "Read-only netsyslog archive DB path"),
        # --- Juniper Mist (cloud API poll) ---
        SettingDef(
            "MIST_ENABLED",
            "0",
            "bool",
            "mist",
            "Poll Juniper Mist cloud for events",
            "Requires MIST_API_KEY — view events on Network hub → Juniper Mist",
        ),
        SettingDef("MIST_API_KEY", "", "secret", "mist", "Juniper Mist API token"),
        SettingDef(
            "MIST_BASE_URL",
            "https://api.eu.mist.com/api/v1",
            "str",
            "mist",
            "Mist API base URL",
            "Use https://api.mist.com/api/v1 for global (non-EU) orgs",
        ),
        SettingDef(
            "MIST_ORG_ID",
            "",
            "str",
            "mist",
            "Mist organization ID",
            "Leave empty to auto-detect from API token",
        ),
        SettingDef("MIST_POLL_INTERVAL_SEC", "300", "int", "mist", "Seconds between Mist polls"),
        SettingDef("MIST_POLL_LIMIT", "100", "int", "mist", "Max events per poll"),
        SettingDef("MIST_LOOKBACK_HOURS", "24", "float", "mist", "Lookback window for each poll"),
    ]


def registry_by_key() -> dict[str, SettingDef]:
    return {d.key: d for d in registry()}
